# Generated by Django 4.1.7 on 2023-06-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('layer', models.CharField(max_length=20)),
                ('shape', models.CharField(blank=True, choices=[('round', 'round'), ('square', 'square'), ('heart', 'heart'), ('other', 'other')], default='round', max_length=20, null=True)),
            ],
        ),
    ]
